### ISSUE TITLE
Quart running under uvicorn with proxy-headers option causes all websockets to return 403

### ISSUE THREAD

**Issue by traverseda** [pallets/quart#221]
You can replicate the bug using this code: https://github.com/traverseda/uvicorn-reverse-proxytest

I suspect an issue with quarts routing, as I understand websockets will return 403 even when it should be returning 404.

Appears to only fail under caddy, you can add this to your caddy file

```Caddyfile
http:// {
        reverse_proxy localhost:8000
}
```

And use the following code example.

```
from quart import Quart, render_template_string, websocket
import asyncio
import logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

app = Quart(__name__)

@app.route("/")
async def hello():
    return await render_template_string("""
<link rel="stylesheet" href="https://unpkg.com/sakura.css/css/sakura.css" type="text/css">
<script src="https://unpkg.com/htmx.org@1.8.5"></script>
<script src="https://unpkg.com/htmx.org/dist/ext/ws.js"></script>

{{url_for("ws")}}
<div hx-ext="ws" ws-connect="{{url_for("ws")}}">
    <div id="ws-value">Websocket not connected</div>
</div>

<hr>
{{request.headers}}
""")

@app.websocket("/ws/")
async def ws():
    enum=0
    while True:
        await websocket.send(f'<div id="ws-value">websocket connected {enum}</div>')
        enum+=1
        await asyncio.sleep(1)

if __name__ == "__main__":
    app.run(host="0.0.0.0")
```

You can run it with `uvicorn app:app  --host 0.0.0.0 --port 8000 --forwarded-allow-ips='*' --proxy-headers`

**Comment by davidism** [comment]
When opening an issue, please include a minimal, reproducible example in the issue itself, rather than asking people to look at a separate page for the actual information.

**Comment by traverseda** [comment]
@davidism In order to reproduce this you need to be running behind a reverse proxy. I don't know how to provide a minimal example that includes a third-party reverse proxy in less than three files.

Would you like me to copy and paste those three files out of that repo and into this issue?

**Comment by traverseda** [comment]
Here's the main code. You'll need to create a new folder and save this as `app.py` into it.

```python
from quart import Quart, render_template_string, websocket
import asyncio
import logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

app = Quart(__name__)

@app.route("/")
async def hello():
    return await render_template_string("""
<link rel="stylesheet" href="https://unpkg.com/sakura.css/css/sakura.css" type="text/css">
<script src="https://unpkg.com/htmx.org@1.8.5"></script>
<script src="https://unpkg.com/htmx.org/dist/ext/ws.js"></script>

{{url_for("ws")}}
<div hx-ext="ws" ws-connect="{{url_for("ws")}}">
    <div id="ws-value">Websocket not connected</div>
</div>

<hr>
{{request.headers}}
""")

@app.websocket("/ws/")
async def ws():
    enum=0
    while True:
        await websocket.send(f'<div id="ws-value">websocket connected {enum}</div>')
        enum+=1
        await asyncio.sleep(1)

if __name__ == "__main__":
    app.run(host="0.0.0.0")
```

Make a Dockerfile with the following contents

```Dockerfile
from python as base
WORKDIR /app
COPY . .
RUN pip install uvicorn quart
```

Finally, in your docker-compose.yaml add the following

```yaml
version: "3.7"
services:
  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
  whoami:
    image: containous/whoami
    labels:
      caddy: http://whoami.localhost https://whoami.localhost
      caddy.reverse_proxy: "{{upstreams 80}}"
  uvicorn:
    build: ./
    ports:
      - 8000:8000
    command: uvicorn app:app  --host 0.0.0.0 --port 8000 --forwarded-allow-ips='*' --proxy-headers
    labels:
      caddy: http://uvicorn.localhost https://uvicorn.localhost
      caddy.reverse_proxy: "{{upstreams 8000}}"
  uvicorn-noheaders:
    build: ./
    command: uvicorn app:app  --host 0.0.0.0 --port 8000 --forwarded-allow-ips='*' --no-proxy-headers
    labels:
      caddy: http://noheaders.localhost https://noheaders.localhost
      caddy.reverse_proxy: "{{upstreams 8000}}"

networks:
  caddy: {}

volumes:
  caddy_data: {}
```

Now run `docker compose up --build` and navigate to https://uvicorn.localhost for an example of quart failing to connect to the web sockets or https://noheaders.localhost for an example where quart connects successfully but uses the incorrect websocket schema.

I'd expect https://uvicorn.localhost to be able to connect to the websocket, instead it's returning a 403 error before it ever gets to the actual user function.
